#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build

WORKDIR /src

COPY ["Services/Product.API/Product.API.csproj","Services/Product.API/"]
COPY ["BuildingBlocks/Common.Logging/Common.Logging.csproj", "BuildingBlocks/Common.Logging/"]
COPY ["BuildingBlocks/Contracts/Contracts.csproj", "BuildingBlocks/Contracts/"]
COPY ["BuildingBlocks/Infrastructure/Infrastructure.csproj", "BuildingBlocks/Infrastructure/"]
COPY ["BuildingBlocks/Shared/Shared.csproj", "BuildingBlocks/Shared/"]

RUN dotnet restore "Services/Product.API/Product.API.csproj"

COPY . .
WORKDIR "/src/Services/Product.API"


RUN dotnet build "Product.API.csproj" -c Release -o /app/build

FROM build as publish

RUN dotnet publish "Product.API.csproj" -c Release -o /app/publish

FROM base as final 
WORKDIR /app

COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Product.API.dll"]